spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/letterflop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

tmdb.api.key=${TMDB_API_KEY:your_api_key_here}
tmdb.api.base-url=https://api.themoviedb.org/3
